apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: px-shared-pvc
  volumeMode: Filesystem

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-block-storage
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: px-db


## Switching to shared
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":{"image-registry-storage"}}}}}'
#
## Switching to block
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":{"image-registry-block-storage"}}}}}'

apiVersion: imageregistry.operator.openshift.io/v1
kind: ConfigMap                                                                                                        
metadata:
  name: cluster
  namespace: openshift-image-registry
spec:                                                      
  defaultRoute: true                                       
  managementState: Managed                                 
  operatorLogLevel: Normal                                 
  proxy: {}                                                
  replicas: 2                                              
  requests:                                                
    read:                                                  
      maxWaitInQueue: 0s                                   
    write:                                                 
      maxWaitInQueue: 0s                                   
  rolloutStrategy: RollingUpdate                           
  storage:                                                 
    pvc:
      claim: image-registry-storage
