bin_dir: /usr/bin
bundle_file: "/tmp/bundle.tar.gz"
removable_media_path: "/tmp/bundle"

ocp_release: 4.6.23
local_registry: "{{ registry_fqdn }}:{{ quay_port }}"
local_repository: ocp4/ocp-release      # needs to exist already
product_repo: openshift-release-dev
release_name: ocp-release
arch: x86_64
cloud_secret: /tmp/pull-secret
merged_secret: /tmp/merged-pull-secret.json
disconnected_registry_user: quayadmin    # needs to be able to write local_repository
disconnected_registry_pass: password
registry_creds: "{{ disconnected_registry_user }}:{{ disconnected_registry_pass }}"
